name: class_resources
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
  firebase_auth:
  cloud_firestore: 
  cloud_functions: ^0.4.0+3
  firebase_messaging: ^5.1.3
  flutter_local_notifications: ^0.8.1+1
  shared_preferences: ^0.5.3+2
  google_sign_in: ^4.0.4
  scoped_model: 
  flutter_masked_text: ^0.8.0
  intl: ^0.15.8
  table_calendar: ^2.0.0
  clipboard_manager: ^0.0.1
  webview_flutter: ^0.3.10+4
  url_launcher: ^5.1.1
  share:
    git:
     url: https://github.com/d-silveira/flutter-share.git
  flutter_downloader: 1.1.6
  path_provider: ^1.2.0
  permission_handler: ^3.2.0
  open_file: 2.0.2
  flutter_svg: ^0.14.0
  googleapis:
  googleapis_auth:
  dynamic_theme: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/ic_launcher.png"
  # image_path_android: "assets/images/ic_launcher.png"
  # image_path_ios: "assets/images/drawing.png"
  android: true # can specify file name here e.g. "ic_launcher"
  # ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_foreground: "assets/images/drawing.png" # only available for Android 8.0 devices and above
  adaptive_icon_background: "#1A73E8" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/ic_launcher.png
    - assets/images/google-logo.png
    - assets/images/google-drive.png
    - assets/images/forget.png
    - assets/images/sent.png
    - assets/images/Login.png
    - assets/images/profile.png
    - assets/images/warning.png
    - assets/images/chore_list.png
    # Photo by ![Nathan Anderson](https://unsplash.com/@nathananderson) on Unsplash
    - assets/images/welcome-bg.jpeg
    - assets/privacy_policy.html
    - assets/file-icons/doc.svg
    - assets/file-icons/exe.svg
    - assets/file-icons/jpg.svg
    - assets/file-icons/png.svg
    - assets/file-icons/mp4.svg
    - assets/file-icons/ppt.svg
    - assets/file-icons/pdf.svg
    - assets/file-icons/xls.svg
    - assets/file-icons/file.svg

    - assets/credientials.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Italic.ttf
          style: italic
